name: Docker CI/CD

on:
  push:
    branches:
      - main  # Replace with your main branch name

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-action@v2

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t user_assistant_image1:latest .
          docker tag user_assistant_image1:latest ${{ secrets.DOCKER_USERNAME }}/user_assistant_image1:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/user_assistant_image1:latest
